apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "amalthea-sessions.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: amalthea
    app.kubernetes.io/part-of: amalthea
  {{- include "amalthea-sessions.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}