apiVersion: v1
data:
  configData:
    "[tasko-personal-polybox]\npass = <sensitive>\ntype = webdav\nuser =
    tolevski\nprovider = \nvendor = owncloud\nurl = https://polybox.ethz.ch/remote.php/webdav/\n\n"
  remote: tasko-personal-polybox
  remotePath: /test-renku-sharing-private
  secretKey: xxxxx
kind: Secret
metadata:
  name: tasko-olevsk-5ccc8a2a7cad-ds-01k349d5x9b747w3c9c25w18nd
  namespace: renku
type: Opaque
---
apiVersion: v1
data:
  pass: xxxxx
kind: Secret
metadata:
  name: tasko-olevsk-5ccc8a2a7cad-ds-01k349d5x9b747w3c9c25w18nd-secrets
  namespace: renku
type: Opaque
