apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: amaltheasessions.amalthea.dev
spec:
  scope: Namespaced
  group: amalthea.dev
  names:
    plural: amaltheasessions
    singular: amaltheasession
    kind: AlmaltheaSession
    shortNames:
    - asn

  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: .status.phase
          description: The current session startup phase
          name: Phase
          type: string
      subresources:
          status: {}

      schema:
        openAPIV3Schema:
          type: object
          description: AmaltheaSession is the Schema for the session API
          properties:
            spec:
              type: object
              description: User defined specification for an Amalthea Session custom resource.
              properties:
                codeRepositories:
                  type: array
                  description: Code that will be pulled into the session
                  items:
                    type: object
                    properties:
                      clonePath:
                        type: string
                        description: Path relative to the root of the work folder to where
                          the repository should be cloned into.
                      git:
                        type: object
                        description: Project's git source
                        properties:
                          remote:
                            type: string
                            description: The remote name.
                          revision:
                            type: string
                            description: The revision to be checkout from. This can
                              be a branch, tag or commit id.
                container:
                  type: object
                  description: session container specification
                  properties:
                    args:
                      type: array
                      description: Arguments passed to the command of the image or the
                        overridden command below.
                      items:
                        type: string
                    command:
                      type: array
                      description: Command to run in place of the image provided
                        command.
                      items:
                        type: string
                    env:
                      type: array
                      description: Environment variables used in this container
                      items:
                        type: object
                        properties:
                          name:
                            type: string
                          value:
                            type: string
                        required:
                        - name
                        - value
                    image:
                      type: string
                    resources:
                      type: object
                      default: {}
                      description: >-
                        Pod resources request
                        example:
                          requests:
                            memory: "64Mi"
                            cpu: "250m"
                          limits:
                            memory: "128Mi"
                            cpu: "500m"
                    name:
                      type: string
                  required:
                  - name

                extraContainers:
                  type: array
                  default: []
                  description: Extra containers to run alongside the main container
                  items:
                    type: object
                    properties:
                      args:
                        type: array
                        description: Arguments passed to the command of the image or the
                          overridden command below.
                        items:
                          type: string
                      command:
                        type: array
                        description: Command to run in place of the image provided
                          command.
                        items:
                          type: string
                      env:
                        type: array
                        description: Environment variables used in this container
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            value:
                              type: string
                          required:
                          - name
                          - value
                      image:
                        type: string
                      resources:
                        type: object
                        default: {}
                        description: >-
                          Pod resources request
                          example:
                            requests:
                              memory: "64Mi"
                              cpu: "250m"
                            limits:
                              memory: "128Mi"
                              cpu: "500m"
                      name:
                        type: string
                    required:
                    - name
                    - image

                initContainers:
                  type: array
                  default: []
                  description: Init containers that run before the rest
                  items:
                    type: object
                    properties:
                      args:
                        type: array
                        description: Arguments passed to the command of the image or the
                          overridden command below.
                        items:
                          type: string
                      command:
                        type: array
                        description: Command to run in place of the image provided
                          command.
                        items:
                          type: string
                      env:
                        type: array
                        description: Environment variables used in this container
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            value:
                              type: string
                          required:
                          - name
                          - value
                      image:
                        type: string
                      resources:
                        type: object
                        default: {}
                        description: >-
                          Pod resources request
                          example:
                            requests:
                              memory: "64Mi"
                              cpu: "250m"
                            limits:
                              memory: "128Mi"
                              cpu: "500m"
                    required:
                    - name
                    - image

                dataSources:
                  type: array
                  default: []
                  description: List of data source to connect to and mount in the main
                    container.
                  items:
                    type: object
                    properties:
                      remote:
                        type: string
                        description: URL of the data source to connect to
                      mountPath:
                        type: string
                        description: Path to were the data source should be mounted
                      secret:
                        type: string
                        description: Name of the secret containing the credentials for the
                          data source.
                    required:
                      - remote
                      - mountPath

                culling:
                  type: object
                  default: {}
                  description: Options about culling idle servers
                  properties:
                    maxAgeSecondsThreshold:
                      type: integer
                      default: 0
                      minimum: 0
                      description:
                        The maximum allowed age for a session, regardless of whether it
                        is active or not. When the threshold is reached the session is hibernated.
                        A value of zero indicates that Amalthea will not automatically hibernate
                        the session based on its age.
                    idleSecondsThreshold:
                      type: integer
                      minimum: 0
                      default: 0
                      description:
                        How long should a server be idle for before it is hibernated. A value of
                        zero indicates that Amalthea will not automatically hibernate inactive sessions.
                    startingSecondsThreshold:
                      type: integer
                      default: 0
                      minimum: 0
                      description:
                        How long can a server be in starting state before it gets hibernated. A
                        value of zero indicates that the server will not be automatically hibernated
                        by Amalthea because it took to long to start.
                    failedSecondsThreshold:
                      type: integer
                      default: 0
                      minimum: 0
                      description:
                        How long can a server be in failed state before it gets hibernated. A
                        value of zero indicates that the server will not be automatically
                        hibernated by Amalthea if it is failing.
                    hibernatedSecondsThreshold:
                      type: integer
                      default: 0
                      minimum: 0
                      description:
                        Number of seconds where a server can be in hibernated state before
                        it gets completely deleted. A value of zero indicates that hibernated servers
                        will not be automatically be deleted by Amalthea after a period of time.
                authentication:
                  type: object
                  default: {}
                  description: OIDC configuration
                  properties:
                    enabled:
                      type: boolean
                      default: false
                      description: Whether OIDC is enabled for this environement
                    configuration:
                      type: object
                      description: Authentication configuration options
                      oneOf:
                        - required:
                            - token
                        - required:
                            - oidc
                      properties:
                        token:
                          type: string
                          description: A pre-generated token that can be used to authenticate a
                            user.
                        configuration:
                          type: object
                          description: Configuration to be applied
                          properties:
                            secretRef:
                              type: string
                              description: Name of the secret containing the OIDC configuration
