kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ name }}
data:
  jupyter_notebook_config.py: |
    import os
    {%- if oidc["enabled"] %}
    c.NotebookApp.ip="127.0.0.1"
    {%- else %}
    c.NotebookApp.ip="0.0.0.0"
    {%- endif %}
    c.NotebookApp.port=8888
    c.NotebookApp.token=os.environ["SERVER_APP_TOKEN"]
    c.NotebookApp.cookie_secret_file="/etc/jupyter_server_secrets/cookie_secret"
    c.NotebookApp.allow_origin="{{ host_url }}"
    c.NotebookApp.base_url="{{ path }}"
    c.NotebookApp.notebook_dir="{{ jupyter_server["rootDir"] }}"
    c.NotebookApp.default_url="{{ jupyter_server["defaultUrl"] }}"
    # Note that we could also just allow non-local hosts in general
    c.NotebookApp.local_hostnames=["localhost", "{{ routing["host"] }}"]

  jupyter_server_config.py: |
    import os
    {%- if oidc["enabled"] %}
    c.ServerApp.ip="127.0.0.1"
    {%- else %}
    c.ServerApp.ip="0.0.0.0"
    {%- endif %}
    c.ServerApp.port=8888
    c.ServerApp.token=os.environ["SERVER_APP_TOKEN"]
    c.ServerApp.cookie_secret_file="/etc/jupyter_server_secrets/cookie_secret"
    c.ServerApp.allow_origin="{{ host_url }}"
    c.ServerApp.base_url="{{ path }}"
    c.ServerApp.root_dir="{{ jupyter_server["rootDir"] }}"
    c.ServerApp.default_url="{{ jupyter_server["defaultUrl"] }}"
    # Note that we could also just allow non-local hosts in general
    c.ServerApp.local_hostnames=["localhost", "{{ routing["host"] }}"]

  authorized-users.txt: |
    {%- for email in oidc["authorizedEmails"] %}
    {{ email }}
    {%- endfor %}
