kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      {% if storage["size"] is not none and storage["size"] != "" %}
      storage: {{ storage["size"] }}
      {% else %}
      storage: 100Mi
      {% endif %}
  {% if "storageClassName" in pvc %}
  storageClassName: {{ pvc["storageClassName"] }}
  {% endif %}
