kind: Secret
apiVersion: v1
metadata:
  name: {{ name }}
type: Opaque
data:
  jupyterServerAppToken: {{ jupyter_server_app_token | b64encode }}
  jupyterServerCookieSecret: {{ jupyter_server_cookie_secret | b64encode }}

  {% if auth["oidc"]["enabled"] and "value" in auth["oidc"]["clientSecret"] %}
  oidcClientSecret: {{ oidc["clientSecret"]["value"] | b64encode }}
  {% else %}
  oidcClientSecret: {{ name | b64encode }}
  {% endif %}

  oauth2ProxyCookieSecret: {{ authentication_plugin_cookie_secret | b64encode }}
