kind: Secret
apiVersion: v1
metadata:
  name: {{ name }}
type: Opaque
data:
  jupyterServerAppToken: {{ jupyter_server_app_token | b64encode }}
  jupyterServerCookieSecret: {{ jupyter_server_cookie_secret | b64encode }}

  {% if auth["oidc"]["enabled"] %}
  oauth2ProxyCookieSecret: {{ authentication_plugin_cookie_secret | b64encode }}
  oauth2ProxyConfig.yaml: |
    upstreams:
      - id: application
        path: "{{ path.rstrip("/") }}/(.*)"
        rewriteTarget: "/$1"
        uri: http://127.0.0.1:8888
        insecureSkipTLSVerify: true
        proxyWebSockets: true
    providers:
      - provider: oidc
        {% if "value" in auth["oidc"]["clientSecret"] %}
        clientSecret: {{ oidc["clientSecret"]["value"] }}
        {% elif "secretKeyRef" in auth["oidc"]["clientSecret"] %}
        clientSecretFile: /etc/oauth2-proxy/oidc-client-secret/{{ auth["oidc"]["clientSecret"]["secretKeyRef"]["key"] }}
        {% endif %}
        clientID: {{ oidc["clientId"] }}
        oidcConfig:
          oidcIssuerURL: {{ oidc["issuerUrl"] }}
        {% if oidc["authorizedGroups"] | length > 0 %}
        allowedGroups:
        {% for group in oidc["authorizedGroups"] %}
          - "{{ group }}"
        {% endfor %}
        {% endif %}
  {% endif %}
