kind: Service
apiVersion: v1
metadata:
  name: {{ name }}
  labels:
    app: {{ name }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      {% if oidc["enabled"] %}
      targetPort: 4180
      {% else %}
      targetPort: 8888
      {% endif %}

  selector:
    app: {{ name }}
  ClusterIP: None
