apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "amalthea.dev/v1alpha1",
          "kind": "AmaltheaSession",
          "metadata": {
            "labels": {
              "app.kubernetes.io/created-by": "amalthea",
              "app.kubernetes.io/instance": "amaltheasession-sample",
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "amaltheasession",
              "app.kubernetes.io/part-of": "amalthea"
            },
            "name": "amaltheasession-sample"
          },
          "spec": null
        }
      ]
    capabilities: Basic Install
    createdAt: "2025-05-26T12:51:04Z"
    operators.operatorframework.io/builder: operator-sdk-v1.38.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: amalthea.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: AmaltheaSession is the Schema for the amaltheasessions API
      displayName: Amalthea Session
      kind: AmaltheaSession
      name: amaltheasessions.amalthea.dev
      statusDescriptors:
      - description: |-
          Conditions store the status conditions of the AmaltheaSessions. This is a standard thing that
          many operators implement see https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties
        displayName: Conditions
        path: conditions
      version: v1alpha1
  description: Operator for running amalthea sessions
  displayName: amalthea
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - amalthea.dev
          resources:
          - amaltheasessions
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - amalthea.dev
          resources:
          - amaltheasessions/finalizers
          verbs:
          - update
        - apiGroups:
          - amalthea.dev
          resources:
          - amaltheasessions/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - apps
          resources:
          - statefulsets
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - events
          - pods
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - delete
          - list
          - patch
          - watch
        - apiGroups:
          - ""
          resources:
          - services
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - metrics.k8s.io
          resources:
          - pods
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - networking.k8s.io
          resources:
          - ingresses
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: amalthea-controller-manager
      deployments:
      - label:
          app.kubernetes.io/component: manager
          app.kubernetes.io/created-by: amalthea
          app.kubernetes.io/instance: controller-manager
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: deployment
          app.kubernetes.io/part-of: amalthea
          control-plane: controller-manager
        name: amalthea-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --metrics-secure
                - --metrics-bind-address=:8443
                - --leader-elect
                - --health-probe-bind-address=:8081
                command:
                - /manager
                image: controller:latest
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
              securityContext:
                runAsNonRoot: true
              serviceAccountName: amalthea-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: amalthea-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - sessions
  links:
  - name: Amalthea
    url: https://amalthea.domain
  maturity: alpha
  provider:
    name: amalthea
  version: 0.0.1
