apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./config.yaml
- ./crd.yaml
- ./deployment.yaml
- ./networkpolicies.yaml
- ./rbac/rbac-namespaced.yaml
- ./rbac/serviceaccount.yaml
