# permissions for end users to edit amaltheasessions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: amaltheasession-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: amalthea
    app.kubernetes.io/part-of: amalthea
    app.kubernetes.io/managed-by: kustomize
  name: amaltheasession-editor-role
rules:
- apiGroups:
  - amalthea.dev.amalthea.dev
  resources:
  - amaltheasessions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - amalthea.dev.amalthea.dev
  resources:
  - amaltheasessions/status
  verbs:
  - get
