# This rule is not used by the project amalthea itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over amalthea.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: amalthea
    app.kubernetes.io/managed-by: kustomize
  name: amaltheasession-admin-role
rules:
- apiGroups:
  - amalthea.dev
  resources:
  - amaltheasessions
  verbs:
  - '*'
- apiGroups:
  - amalthea.dev
  resources:
  - amaltheasessions/status
  verbs:
  - get
