
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - amalthea.dev.olevski90
  resources:
  - jupyterservers/finalizers
  verbs:
  - update
- apiGroups:
  - amalthea.dev.olevski90
  resources:
  - jupyterservers/status
  verbs:
  - get
  - patch
  - update
