{{- if .Values.deployCrd -}}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: {{ .Values.crdNames.plural }}.{{ .Values.crdApiGroup }}
spec:
  scope: Namespaced
  group: {{ .Values.crdApiGroup }}
  names:
    kind: {{ .Values.crdNames.kind }}
    plural: {{ .Values.crdNames.plural }}
    singular: {{ .Values.crdNames.singular }}
    shortNames:
    {{- range .Values.crdNames.shortNames }}
      - {{ . }}
    {{- end }}
  versions:
    - name: {{ .Values.crdApiVersion }}
      served: true
      storage: true
      additionalPrinterColumns:
      - name: Image
        type: string
        description: The Jupyter server image that is running
        jsonPath: .spec.jupyterServer.image
      - name: URL
        type: string
        description: Full URL where the server can be reached
        jsonPath: .status.create_fn.fullServerURL
      - name: Pod Status
        type: string
        description: Status of the main pod
        jsonPath: .status.mainPod.status.phase

      schema:
        openAPIV3Schema:
          type: object
          properties:
            {{- .Files.Get "crd-spec.yaml" | nindent 12 -}}
            status:
              description: A field for Jupyter Server status information, do not modify.
              type: object
              x-kubernetes-preserve-unknown-fields: true
              default:
                children: {}
                mainPod: {}
{{- end }}
