{{- if .Values.deployCrd -}}
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jupyterservers.renku.io
spec:
  scope: Namespaced
  group: renku.io
  names:
    kind: JupyterServer
    plural: jupyterservers
    singular: jupyterserver
    shortNames:
      - js
  versions:
    - name: v1alpha1
      served: true
      storage: true
      additionalPrinterColumns:
      - name: Image
        type: string
        description: The Jupyter server image that is running
        jsonPath: .spec.jupyterServer.image
      - name: Host
        type: string
        description: Host under which the server can be reached
        jsonPath: .spec.routing.host
      - name: Path
        type: string
        description: Path under which the server can be reached
        jsonPath: .spec.routing.path
      - name: Pod Status
        type: string
        description: Status of the main pod
        jsonPath: .status.mainPod.status.phase

      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              default:
                children: {}
                mainPod: {}
            spec:
              type: object
              properties:

                jupyterServer:
                  type: object
                  default: {} # Stupid, but necessary for the inner defaults do work
                  properties:
                    image:
                      type: string
                      default: jupyter/minimal-notebook:latest
                    defaultUrl:
                      type: string
                      default: /lab
                    rootDir:
                      type: string
                      default: /home/jovyan/work/

                    # TODO: Automatically fetch and inline schema
                    # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#resourcerequirements-v1-core
                    resources:
                      description: "Regular resource requests, will be set on the main notebook container."
                      type: object
                      x-kubernetes-preserve-unknown-fields: true

                routing:
                  type: object
                  default: {} # Stupid, but necessary for the inner defaults do work
                  properties:
                    host:
                      type: string
                    path:
                      type: string
                      default: "/"
                    tlsSecret:
                      type: string
                    ingressAnnotations:
                      type: string

                storage:
                  type: object
                  properties:
                    size:
                      description: "Size of the PVC or sizeLimit of the emptyDir volume which backs the session respectively."
                      type: string
                      default: 100Mi
                    pvc:
                      type: object
                      properties:
                        enabled:
                          description: "Wether a PVC should be used to back the session. Defaults to 'false' in which case an emptyDir volume will be used."
                          type: boolean
                          default: false
                        storageClassName:
                          type: string
                          description: "Storage class to be used for the PVC. If left empty, the default storage class defined for the cluster will be used."

                auth:
                  type: object
                  default: {} # Stupid, but necessary for the inner defaults do work
                  properties:
                    cookieWhiteList:
                      type: array
                      default: ["username-localhost-8888", "_xsrf"]
                      items:
                        type: string
                    # As soon as a cookie black list is defined, the white list is ignored.
                    cookieBlackList:
                      type: array
                      items:
                        type: string
                    token:
                      type: string
                    oidc:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                          default: False
                        issuerUrl:
                          type: string
                        clientId:
                          type: string
                        clientSecret:
                          type: string
                        userId:
                          type: string

                patches:
                  description: "Patches to be applied. Currently only json patches and json merge patches are supported."
                  type: array
                  default: []
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                        enum:
                          - application/json-patch+json
                          - application/merge-patch+json
                      patch:
                        x-kubernetes-preserve-unknown-fields: true
{{- end }}
