{{- if .Values.networkPolicies.controller.denyAllIngress -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "amalthea.fullname" . }}-controller
  labels:
    {{- include "amalthea.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "amalthea.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller
  policyTypes:
    - Ingress
{{- end -}}

{{- if and (or .Values.networkPolicies.sessions.ingress.restrict .Values.networkPolicies.sessions.egress.restrict) (not .Values.scope.clusterWide) -}}
{{- range (.Values.scope.namespaces | default (list .Release.Namespace)) }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ . }}
  name: {{ include "amalthea.fullname" $ }}-jupyterserver
  labels:
    {{- include "amalthea.labels" $ | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "amalthea.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: jupyterserver
  policyTypes:
    - Ingress
    - Egress
{{- if $.Values.networkPolicies.sessions.ingress.restrict -}}
  ingress:
    - ports:
        - protocol: TCP
          port: 8000
      from:
        - podSelector:
            matchLabels:
              {{- $.Values.networkPolicies.sessions.ingress.podSelectorLabels | toYaml | nindent 14 }}
          namespaceSelector:
            matchLabels:
              {{- $.Values.networkPolicies.sessions.ingress.namespaceSelectorLabels | toYaml | nindent 14 }}
{{- end -}}
{{- if $.Values.networkPolicies.sessions.egress.restrict -}}
  egress:
  - to:
    # Allow DNS resolution (internal and external)
    ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  - to:
    # Allow access to web outside of cluster by excluding
    # IP ranges which are reserved for private networking from
    # the allowed range.
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
    ports:
    - port: 80
      protocol: TCP
    - port: 443
      protocol: TCP
{{- end -}}
{{- end }}
{{- else -}}
{{- fail "Network policies for the sessions cannot be applied for a cluster wide amalthea deployment." }}
{{- end -}}
