{{- if .Values.networkPolicies.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "amalthea.fullname" . }}-controller
  labels:
    {{- include "amalthea.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "amalthea.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: controller
  policyTypes:
    - Ingress
  {{- if .Values.metrics.enabled  }}
  ingress:
    - from:
      # Allow ingress only to the metrics (if enabled)
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: {{ .Values.metrics.port }}
  {{- end }}
{{ if and .Values.networkPolicies.enabled ( not .Values.scope.clusterWide ) }}
{{- range (.Values.scope.namespaces | default (list .Release.Namespace)) -}}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  namespace: {{ . }}
  name: {{ include "amalthea.fullname" $ }}-jupyterserver
  labels:
    {{- include "amalthea.labels" $ | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "amalthea.selectorLabels" $ | nindent 6 }}
      app.kubernetes.io/component: jupyterserver
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      # Allow ingress only to the oauth2proxy
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 4180
  egress:
    - to:
      # Allow DNS resolution (internal and external)
      ports:
      - port: 53
        protocol: UDP
      - port: 53
        protocol: TCP
    - to:
      # Allow access to any port/protocol as long as it is directed
      # outside of the cluster. This is done by excluding
      # IP ranges which are reserved for private networking from
      # the allowed range.
      - ipBlock:
          cidr: 0.0.0.0/0
          except:
          - 10.0.0.0/8
          - 172.16.0.0/12
          - 192.168.0.0/16
{{- end }}
{{- end }}
{{- end }}

{{- if and .Values.networkPolicies.enabled .Values.scope.clusterWide -}}
{{- fail "Network policies for the jupuyter servers cannot be applied for a cluster wide amalthea deployment." -}}
{{- end -}}
