apiVersion: amalthea.dev/v1alpha1
kind: AmaltheaSession
metadata:
  labels:
    app.kubernetes.io/name: amalthea
    app.kubernetes.io/managed-by: kustomize
  name: amaltheasession-sample
spec:
  # TODO(user): Add fields here
