//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JupyterServer) DeepCopyInto(out *JupyterServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	out.Secrets = in.Secrets
	out.Aux = in.Aux
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JupyterServer.
func (in *JupyterServer) DeepCopy() *JupyterServer {
	if in == nil {
		return nil
	}
	out := new(JupyterServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JupyterServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JupyterServerAux) DeepCopyInto(out *JupyterServerAux) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JupyterServerAux.
func (in *JupyterServerAux) DeepCopy() *JupyterServerAux {
	if in == nil {
		return nil
	}
	out := new(JupyterServerAux)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JupyterServerList) DeepCopyInto(out *JupyterServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]JupyterServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JupyterServerList.
func (in *JupyterServerList) DeepCopy() *JupyterServerList {
	if in == nil {
		return nil
	}
	out := new(JupyterServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *JupyterServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JupyterServerSecret) DeepCopyInto(out *JupyterServerSecret) {
	*out = *in
	out.SecretKeyRef = in.SecretKeyRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JupyterServerSecret.
func (in *JupyterServerSecret) DeepCopy() *JupyterServerSecret {
	if in == nil {
		return nil
	}
	out := new(JupyterServerSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JupyterServerSecretKeyRef) DeepCopyInto(out *JupyterServerSecretKeyRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JupyterServerSecretKeyRef.
func (in *JupyterServerSecretKeyRef) DeepCopy() *JupyterServerSecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(JupyterServerSecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JupyterServerSecrets) DeepCopyInto(out *JupyterServerSecrets) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JupyterServerSecrets.
func (in *JupyterServerSecrets) DeepCopy() *JupyterServerSecrets {
	if in == nil {
		return nil
	}
	out := new(JupyterServerSecrets)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JupyterServerSpec) DeepCopyInto(out *JupyterServerSpec) {
	*out = *in
	in.Auth.DeepCopyInto(&out.Auth)
	out.Culling = in.Culling
	in.JupyterServer.DeepCopyInto(&out.JupyterServer)
	if in.Patches != nil {
		in, out := &in.Patches, &out.Patches
		*out = make([]JupyterServerSpecPatch, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Routing.DeepCopyInto(&out.Routing)
	out.Storage = in.Storage
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JupyterServerSpec.
func (in *JupyterServerSpec) DeepCopy() *JupyterServerSpec {
	if in == nil {
		return nil
	}
	out := new(JupyterServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JupyterServerSpecAuth) DeepCopyInto(out *JupyterServerSpecAuth) {
	*out = *in
	in.Oidc.DeepCopyInto(&out.Oidc)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JupyterServerSpecAuth.
func (in *JupyterServerSpecAuth) DeepCopy() *JupyterServerSpecAuth {
	if in == nil {
		return nil
	}
	out := new(JupyterServerSpecAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JupyterServerSpecAuthOidc) DeepCopyInto(out *JupyterServerSpecAuthOidc) {
	*out = *in
	if in.AuthorizedEmails != nil {
		in, out := &in.AuthorizedEmails, &out.AuthorizedEmails
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AuthorizedGroups != nil {
		in, out := &in.AuthorizedGroups, &out.AuthorizedGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	out.ClientSecret = in.ClientSecret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JupyterServerSpecAuthOidc.
func (in *JupyterServerSpecAuthOidc) DeepCopy() *JupyterServerSpecAuthOidc {
	if in == nil {
		return nil
	}
	out := new(JupyterServerSpecAuthOidc)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JupyterServerSpecCulling) DeepCopyInto(out *JupyterServerSpecCulling) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JupyterServerSpecCulling.
func (in *JupyterServerSpecCulling) DeepCopy() *JupyterServerSpecCulling {
	if in == nil {
		return nil
	}
	out := new(JupyterServerSpecCulling)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JupyterServerSpecJupyterServer) DeepCopyInto(out *JupyterServerSpecJupyterServer) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JupyterServerSpecJupyterServer.
func (in *JupyterServerSpecJupyterServer) DeepCopy() *JupyterServerSpecJupyterServer {
	if in == nil {
		return nil
	}
	out := new(JupyterServerSpecJupyterServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JupyterServerSpecPatch) DeepCopyInto(out *JupyterServerSpecPatch) {
	*out = *in
	if in.Patch != nil {
		in, out := &in.Patch, &out.Patch
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JupyterServerSpecPatch.
func (in *JupyterServerSpecPatch) DeepCopy() *JupyterServerSpecPatch {
	if in == nil {
		return nil
	}
	out := new(JupyterServerSpecPatch)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JupyterServerSpecRouting) DeepCopyInto(out *JupyterServerSpecRouting) {
	*out = *in
	if in.IngressAnnotations != nil {
		in, out := &in.IngressAnnotations, &out.IngressAnnotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.Tls = in.Tls
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JupyterServerSpecRouting.
func (in *JupyterServerSpecRouting) DeepCopy() *JupyterServerSpecRouting {
	if in == nil {
		return nil
	}
	out := new(JupyterServerSpecRouting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JupyterServerSpecRoutingTls) DeepCopyInto(out *JupyterServerSpecRoutingTls) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JupyterServerSpecRoutingTls.
func (in *JupyterServerSpecRoutingTls) DeepCopy() *JupyterServerSpecRoutingTls {
	if in == nil {
		return nil
	}
	out := new(JupyterServerSpecRoutingTls)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JupyterServerSpecStorage) DeepCopyInto(out *JupyterServerSpecStorage) {
	*out = *in
	out.Pvc = in.Pvc
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JupyterServerSpecStorage.
func (in *JupyterServerSpecStorage) DeepCopy() *JupyterServerSpecStorage {
	if in == nil {
		return nil
	}
	out := new(JupyterServerSpecStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JupyterServerSpecStoragePvc) DeepCopyInto(out *JupyterServerSpecStoragePvc) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JupyterServerSpecStoragePvc.
func (in *JupyterServerSpecStoragePvc) DeepCopy() *JupyterServerSpecStoragePvc {
	if in == nil {
		return nil
	}
	out := new(JupyterServerSpecStoragePvc)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JupyterServerStatus) DeepCopyInto(out *JupyterServerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JupyterServerStatus.
func (in *JupyterServerStatus) DeepCopy() *JupyterServerStatus {
	if in == nil {
		return nil
	}
	out := new(JupyterServerStatus)
	in.DeepCopyInto(out)
	return out
}
