{% extends "base/configmap-proxy.yaml" %}
{% block traefik_dynamic_config %}
  traefik-dynamic-config.yaml: |
    http:
      routers:
        to-server:
          rule: "PathPrefix(`{{ path }}`)"
          service: server
          {% if basic_auth["enabled"] and not oidc["enabled"] %}
          middlewares:
            - basicAuth
          {% endif %}
      services:
        server:
          loadBalancer:
            servers:
            - url: http://localhost:8888
      {% if basic_auth["enabled"] and not oidc["enabled"] %}
      middlewares:
        basicAuth:
          basicAuth:
            users:
              - "{{ basic_auth["username"] }}:{{ basic_auth["password"] | bcrypt }}"
            removeHeader: true
      {% endif %}
{% endblock %}
