apiVersion: amalthea.dev/v1alpha1
kind: JupyterServer
metadata:
  name: ## ADD NAME
  namespace: ## ADD NAMESPACE
spec:
  routing:
    host: ## Add hostname
  auth:
    kind: oidc
    oidc:
      issuerUrl: ## Issuer URL of OIDC provider
      clientId: ## Client ID of registered application
      clientSecret: ## Client secret of registered application
      authorizedEmails:
        []
        ## Email address of the user who is allowed access this server
        # - me@example.com
        # - myfriend@example.com
