apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: jupyterservers.renku.io
spec:
  scope: Namespaced
  group: renku.io
  names:
    kind: JupyterServer
    plural: jupyterservers
    singular: jupyterserver
    shortNames:
      - js
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:

                jupyterServer:
                  type: object
                  default: {} # Stupid, but necessary for the inner defaults do work
                  properties:
                    image:
                      type: string
                      default: jupyter/minimal-notebook:latest
                    defaultUrl:
                      type: string
                      default: /lab
                    rootDir:
                      type: string
                      default: /home/jovyan/work/

                    # TODO: Automatically fetch and inline schema
                    # https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.20/#resourcerequirements-v1-core
                    resources:
                      description: "Regular resource requests, will be set on the main notebook container."
                      type: object
                      x-kubernetes-preserve-unknown-fields: true

                routing:
                  type: object
                  default: {} # Stupid, but necessary for the inner defaults do work
                  properties:
                    host:
                      type: string
                    path:
                      type: string
                      default: "/"

                volume:
                  type: object
                  default: {} # Stupid, but necessary for the inner defaults do work
                  properties:
                    size:
                      type: string
                      default: 100Mi
                    storageClass:
                      type: string

                auth:
                  type: object
                  default: {} # Stupid, but necessary for the inner defaults do work
                  properties:
                    cookieWhiteList:
                      type: array
                      default: ["username-localhost-8888", "_xsrf"]
                      items:
                        type: string
                    # As soon as a cookie black list is defined, the white list is ignored.
                    cookieBlackList:
                      type: array
                      items:
                        type: string
                    token:
                      type: string
                    oidc:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                          default: False
                        issuerUrl:
                          type: string
                        clientId:
                          type: string
                        clientSecret:
                          type: string
                        userId:
                          type: string


                resourceModifications:
                  description: "Modifications to be applied to the resources which are part of this custom object OR containers in the statefulset component. We use python deepmerge."
                  type: array
                  default: []
                  items:
                    type: object
                    properties:
                      resource:
                        type: string
                      modification:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true

                extraResources:
                  description: "Extra Resources to be created with the custom resource object."
                  type: array
                  default: []
                  items:
                    type: object
                    properties:
                      api:
                        type: string
                      creationMethod:
                        type: string
                      resourceSpec:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true

