kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: {{ name }}
  annotations: {{ routing["ingressAnnotations"] }}
spec:
{% if routing['tls']['enabled'] %}
  tls:
    - hosts:
        - {{ routing["host"] }}
      secretName: {{ routing["tls"]["secret"] }}
{% endif %}
  rules:
    - host: {{ routing["host"] }}
      http:
        paths:
        - path: {{ path }}
          backend:
            serviceName: {{ name }}
            servicePort: 80
