kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {name}
  namespace: {namespace}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {volume_size}
  storageClassName: {volume_storage_class}
