kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ storage["size"] }}
  {% if "storageClassName" in pvc %}
  storageClassName: {{ pvc["storageClassName"] }}
  {% endif %}
