kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ name }}
spec:
  selector:
    matchLabels:
      app: {{ name }}
  serviceName: {{ name }}
  # Scaling up is not intended and won't work
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ name }}
    spec:
      imagePullSecrets: []
      initContainers: []
      volumes:
        - name: traefik-configmap
          configMap:
            name: {{ name }}
            defaultMode: 420
        {% if pvc["enabled"] %}
        - name: workspace
          persistentVolumeClaim:
            claimName: {{ name }}
        {% else %}
        - name: workspace
          emptyDir:
            sizeLimit: {{ storage["size"] }}
        {% endif %}
      terminationGracePeriodSeconds: 30
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 100

      containers:
        - name: jupyter-server
          image: {{ jupyter_server["image"] }}
          entrypoint: ["tini", "-g", "--"]
          command:
            - start-notebook.sh
          args:
          # TODOs:
          # - Move these configurations to a configmap and mount it as jupyter_notebook_config.py and
          #   jupyter_server_config.py respectively.
          # - Drop support for jupyter notebook.
            - "--ServerApp.ip=0.0.0.0"
            - "--NotebookApp.ip=0.0.0.0"
            - "--ServerApp.port=8888"
            - "--NotebookApp.port=8888"
            - "--ServerApp.token={{ auth["token"] }}"
            - "--NotebookApp.token={{ auth["token"] }}"
            - "--ServerApp.allow_origin={{ host_url }}"
            - "--NotebookApp.allow_origin={{ host_url }}"
            - "--ServerApp.base_url={{ path }}"
            - "--NotebookApp.base_url={{ path }}"
            - "--ServerApp.root_dir={{ jupyter_server["rootDir"] }}"
            - "--NotebookApp.notebook_dir={{ jupyter_server["rootDir"] }}"
            - "--ServerApp.default_url={{ jupyter_server["defaultUrl"] }}"
            - "--NotebookApp.default_url={{ jupyter_server["defaultUrl"] }}"
          workingDir: {{ jupyter_server["rootDir"] }}
          volumeMounts:
            - name: workspace
              mountPath: {{ jupyter_server["rootDir"] }}
              subPath: work
          ports:
            - name: notebook-port
              containerPort: 8888
              protocol: TCP
          securityContext:
            runAsUser: 1000
            runAsGroup: 100
            fsGroup: 100
            allowPrivilegeEscalation: false


        - name: auth-proxy
          image: "traefik:2.1.4"
          args:
            - "--configfile=/config/traefik.yaml"
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          resources:
            requests:
              cpu: 20m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 32Mi
          volumeMounts:
            - name: traefik-configmap
              mountPath: /config
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 1

        - name: cookie-cleaner
          image: ableuler/cookie-cleaner:0.0.0-9
          env:
            - name: ALLOWLIST
              value: '{{ cookie_allowlist }}'
            - name: BLOCKLIST
              value: '{{ cookie_blocklist }}'
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          resources:
            requests:
              cpu: 20m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 32Mi

        {% if oidc["enabled"] %}
        - name: authorization-plugin
          image: ableuler/auth-test:0.0.0-1
          env:
            - name: USER_ID
              value: {{ oidc["userId"] }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: 20m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 32Mi

        - name: authentication-plugin
          image: "bitnami/oauth2-proxy:7.1.2"
          args:
            - "--provider=oidc"
            - "--client-id={{ oidc["clientId"] }}"
            - "--client-secret={{ oidc["clientSecret"] }}"
            - "--oidc-issuer-url={{ oidc["issuerUrl"] }}"
            - "--session-cookie-minimal"
            - "--set-xauthrequest"
            - "--cookie-secret={{ cookie_secret }}"
            - "--email-domain=*"
            - "--http-address=:4180"
            - "--skip-provider-button"
            - "--reverse-proxy"
            - "--upstream=static://202"
            - "--redirect-url={{ full_url }}/oauth2/callback"
          ports:
            - name: http
              containerPort: 4180
              protocol: TCP
          resources:
            requests:
              cpu: 20m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 32Mi
        {% endif %}
