{{- if .Values.serviceAccount.create -}}
{{- if .Values.scope.clusterWide }}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "amalthea.fullname" . }}
  labels:
    {{- include "amalthea.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "amalthea.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "amalthea.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "amalthea.fullname" . }}
  labels:
    {{- include "amalthea.labels" . | nindent 4 }}
{{- template "amalthea.rules" }}

{{- end }}
{{- end }}


