kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ name }}
data:
  {% block configmap %}
  {% endblock %}

  {% if oidc["enabled"] %}
  authorized-users.txt: |
    {%- for email in oidc["authorizedEmails"] %}
    {{ email }}
    {%- endfor %}
  {% endif %}

  traefik-static-config.yaml: |
    accessLog: {} 
    log:
      level: DEBUG
    entryPoints:
      web:
        address: :4181
      miscInternal:
        address: :4182
    metrics:
      prometheus:
        entryPoint: miscInternal
        addEntryPointsLabels: true
        addRoutersLabels: true
        addServicesLabels: false
    ping:
      entryPoint: miscInternal
    api:
      dashboard: true
      insecure: true
      debug: true
    providers:
      file:
        directory: "/traefik"
