kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ name }}
spec:
  selector:
    matchLabels:
      app: {{ name }}
  serviceName: {{ name }}
  # Scaling up is not intended and won't work
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ name }}
    spec:
      imagePullSecrets: []
      initContainers: []
      volumes:
        {% if oidc["enabled"] %}
        - name: oauth2-proxy-config
          configMap:
            name: {{ name }}
            items:
              - key: authorized-users.txt
                path: authorized-users.txt
        {% else %}
        - name: traefik-dynamic-config
          configMap:
            name: {{ name }}
            items:
              - key: traefik-dynamic-config.yaml
                path: traefik-dynamic-config.yaml
        {% endif %}
        {% block volumes scoped %}
        {% endblock %}
        {% if pvc["enabled"] %}
        - name: workspace
          persistentVolumeClaim:
            claimName: {{ name }}
        {% else %}
        - name: workspace
          emptyDir:
            {% if storage["size"] is not none and storage["size"] != "" %}
            sizeLimit: {{ storage["size"] }}
            {% endif %}
        {% endif %}
      terminationGracePeriodSeconds: 30
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 100
      enableServiceLinks: false
      {% if scheduler_name %}
      schedulerName: {{ scheduler_name }}
      {% endif %}
      containers:
        {% block containers scoped required %}
        {% endblock %}
        
        {% if oidc["enabled"] %}
        - name: oauth2-proxy
          image: "bitnami/oauth2-proxy:7.1.3"
          args:
            - "--provider=oidc"
            - "--client-id={{ oidc["clientId"] }}"
            - "--oidc-issuer-url={{ oidc["issuerUrl"] }}"
            - "--session-cookie-minimal"
            - "--http-address=:4180"
            - "--skip-provider-button"
            - "--upstream=http://127.0.0.1:8888"
            - "--redirect-url={{ full_url }}/oauth2/callback"
            - "--cookie-path={{ path }}"
            - "--proxy-prefix={{ path if path != '/' else '' }}/oauth2"
            - "--authenticated-emails-file=/etc/oauth2-proxy/authorized-users.txt"
            {% block extraAuthProxyArgs scoped %}
            {% endblock %}
            {% for group in oidc["authorizedGroups"] %}
            - "--allowed-group={{ group }}"
            {% endfor %}
          ports:
            - name: http
              containerPort: 4180
              protocol: TCP
          env:
            - name: OAUTH2_PROXY_COOKIE_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ name }}
                  key: oauth2ProxyCookieSecret
            - name: OAUTH2_PROXY_CLIENT_SECRET
              valueFrom:
              {% if "value" in auth["oidc"]["clientSecret"] %}
                secretKeyRef:
                  name: {{ name }}
                  key: oidcClientSecret
              {% endif %}
              {% if "secretKeyRef" in auth["oidc"]["clientSecret"] %}
                secretKeyRef:
                  name: {{ auth["oidc"]["clientSecret"]["secretKeyRef"]["name"] }}
                  key: {{ auth["oidc"]["clientSecret"]["secretKeyRef"]["key"] }}
              {% endif %}
          volumeMounts:
            - name: oauth2-proxy-config
              mountPath: /etc/oauth2-proxy/authorized-users.txt
              subPath: authorized-users.txt
          resources:
            requests:
              cpu: 20m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 32Mi
        {% else %}
        - name: passthrough-proxy
          image: traefik:v2.5
          args:
           - --entryPoints.web.address=:4180
           - --providers.file.directory=/traefik
          ports:
            - name: http
              containerPort: 4180
              protocol: TCP
          volumeMounts:
            - name: traefik-dynamic-config
              mountPath: /traefik/traefik-dynamic-config.yaml
              subPath: traefik-dynamic-config.yaml
          resources:
            requests:
              cpu: 20m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
        {% endif %}
