kind: Secret
apiVersion: v1
metadata:
  name: {{ .Name }}
  ownerReferences:
    - apiVersion: {{ .APIVersion }}
      blockOwnerDeletion: false
      controller: true
      kind: {{ .Kind }}
      name: {{ .Name }}
      uid: {{ .UID }}
type: Opaque
data:
  jupyterServerAppToken: {{ .Secrets.JupyterServerAppToken | b64enc }}
  jupyterServerCookieSecret: {{ .Secrets.JupyterServerCookieSecret | b64enc }}

  {{ if .Spec.Auth.Oidc.Enabled }}
  {{ if .Spec.Auth.Oidc.ClientSecret.Value }}
  oidcClientSecret: {{ .Spec.Auth.Oidc.ClientSecret.Value | b64enc }}
  {{ end }}
  oauth2ProxyCookieSecret: {{ .Secrets.AuthProviderCookieSecret | b64enc }}
  {{ end }}
