name: Autogenerate the manifests and documentation for the CRD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  
  push-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Push the image for the current commit
        env:
          DOCKER_USERNAME: ${{ secrets.RENKU_DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.RENKU_DOCKER_PASSWORD }}
        run: |
          echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
          python -m pip install --upgrade pip pipenv
          pipenv install --dev
          pipenv run chartpress --tag $(git rev-parse HEAD) --push
          pipenv run chartpress --tag latest --push
