name: Autogenerate the manifests and documentation for the CRD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-crd-docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Render chart into manifests
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            make crd
          push: never
          skipContainerUserIdUpdate: false
      - name: Generate CRD documentation
        uses: SwissDataScienceCenter/renku-actions/generate-crd-docs@v1.11.3
        env:
          RESOURCES: ./manifests/crd.yaml
          OUTPUT: ./docs/crd.md
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        env:
          GITHUB_TOKEN: ${{ secrets.RENKUBOT_GITHUB_TOKEN }}
        with:
          commit-message: "chore: update rendered manifests and CRD docs"
          delete-branch: true
          title: Update rendered manifests and CRD docs
          author: "Renku Bot <renku@datascience.ch>"
          committer: "Renku Bot <renku@datascience.ch>"
          branch: renkubot/update-manifests-docs-
          branch-suffix: timestamp
