name: Autogenerate the manifests and documentation for the CRD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  chart-manifests-CRDDocs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install python packages
        if:
          "!(startsWith(github.event.head_commit.message, 'chore: prep') &&
          endsWith(github.event.head_commit.message, 'release'))"
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install --dev
      - name: Set appVersion and push images
        if:
          "!(startsWith(github.event.head_commit.message, 'chore: prep') &&
          endsWith(github.event.head_commit.message, 'release'))"
        env:
          DOCKER_USERNAME: ${{ secrets.RENKU_DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.RENKU_DOCKER_PASSWORD }}
          # Figure out the short commit hash of the last commit that
          # might have modified the image and update the appVersion accordingly.
        run: |
          echo ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
          PATHS=$(ls | grep -v manifests | grep -v helm-chart | grep -v CHANGELOG.md)
          TAG=$(git log -n 1 --pretty=format:%H -- $PATHS)
          sed -i'' -e 's/^appVersion: .*/appVersion: '"${TAG:0:7}"'/g'  helm-chart/amalthea/Chart.yaml
          cd helm-chart/
          pipenv run chartpress --tag ${TAG:0:7} --push
          pipenv run chartpress --tag latest --push
          pipenv run chartpress --reset
          cd ../
      - name: Render chart into manifests
        if:
          "!(startsWith(github.event.head_commit.message, 'chore: prep') &&
          endsWith(github.event.head_commit.message, 'release'))"
        run: |
          pipenv run python utils/render-chart-manifests.py
      - name: Generate CRD documentation
        uses: SwissDataScienceCenter/renku-actions/generate-crd-docs@3d6f5abf79b61d969b0d958e42dabb4e9f15392c
        env:
          RESOURCES: ./manifests/crd.yaml
          OUTPUT: ./docs/crd.md
      - name: Create pull request
        if:
          "!(startsWith(github.event.head_commit.message, 'chore: prep') &&
          endsWith(github.event.head_commit.message, 'release'))"
        uses: peter-evans/create-pull-request@v3
        env:
          GITHUB_TOKEN: ${{ secrets.RENKUBOT_GITHUB_TOKEN }}
        with:
          commit-message: "chore: update rendered manifests and CRD docs"
          delete-branch: true
          title: Update rendered manifests and CRD docs
