name: Unit Tests

on:
  pull_request:
    types:
    - opened
    - edited
    - synchronize
    - reopened
    - closed

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Run unit tests
        run: |
          python -m pip install --upgrade pip pipenv
          pipenv install --deploy --system --dev
          pipenv run pytest tests/unit
